version: '3.4'

services:
 catalogdb:
  container_name: catalogdb
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=CatalogDb
  restart: always
  ports:
      - "5432:5432"
  volumes:
    - postgres_catalog:/var/lib/postgresql/data/

 catalogapi: 
    build: 
      context: ./Services/Catalog/Catalog.API 
      dockerfile: Dockerfile 
    container_name: catalogapi 
    environment: 
      ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: "true" 
      DOTNET_USE_POLLING_FILE_WATCHER: "1" 
      NUGET_FALLBACK_PACKAGES: "" 
    ports: 
      - "8080:8080" 
      - "8081:8081" 
    volumes: 
      - ./Services/Catalog/Catalog.API:/app